name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Create a model with...
        2. Call the method...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: php
      placeholder: |
        <?php
        // Your code here

  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you running?
      options:
        - 8.3
        - 8.2
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: laravel-version
    attributes:
      label: Laravel Version
      description: What version of Laravel are you using?
      options:
        - 11.x
        - 10.x
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of litepie/database are you using?
      placeholder: e.g., 2.0.0
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment details
      description: |
        Please provide details about your environment:
        - Operating System
        - Database (MySQL, PostgreSQL, SQLite, etc.)
        - Cache driver (Redis, Memcached, etc.)
      placeholder: |
        - OS: Ubuntu 22.04
        - Database: MySQL 8.0
        - Cache: Redis 7.0

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, including stack traces, logs, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
