name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe the use case for this feature. How would you use it?
      placeholder: |
        This feature would be useful when...
        
        Example usage:
        ```php
        // Your example code here
        ```

  - type: dropdown
    id: trait-category
    attributes:
      label: Which trait/component would this feature affect?
      options:
        - Archivable
        - Cacheable
        - Searchable
        - Sluggable
        - Sortable
        - Casts (JSON/Money)
        - Model Macros
        - Migration Macros
        - Other/New Component
        - Not sure

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (simple addition/modification)
        - Medium (moderate changes required)
        - High (significant changes/new functionality)
        - Not sure

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes
        - label: This feature could be implemented without breaking changes
        - label: I'm not sure about breaking changes

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
